version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
      - .:/app
    environment:
      - FLASK_ENV=development
